feat. OriginSplitJoin
intellistream/AllianceDB pull request #61
Opened 2023-02-28 12:55 UTC by whyy7777

1, OriginSplitJoin
2, EmitAllWindow

2023-02-28 13:01 UTC, wzru requested changes
Use clang-format to format codes :)

2023-02-28 14:53 UTC, whyy7777 commented on include/Common/Result.hpp
> +    void EmitAllWindow(TuplePtr t1, TuplePtr t2);
I think it is more explicit after renaming

2023-02-28 15:05 UTC, whyy7777 commented on .gitignore
> +./DS_Store
done

2023-02-28 15:33 UTC, wzru commented on .gitignore
> +.DS_Store/
.DS_Store still exists...

2023-02-28 15:34 UTC, wzru commented on test/System/Test.cpp
> +    ctx.res->Print();
remove this

2023-02-28 15:40 UTC, whyy7777 commented on test/System/Test.cpp
> +    ctx.res->Print();
done

2023-02-28 15:40 UTC, whyy7777 commented on .gitignore
> +.DS_Store/
done

2023-03-01 02:55 UTC, wzru approved these changes

2023-03-01 02:56 UTC, merged